name: Simple Workflow

on: 
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: 
  
jobs: 
  deploy:
    environment: prod
    name: Simple workflow
    runs-on: ubuntu-latest
    steps: 
      - name: list items
        run: ls -a